import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { Navbar } from "@/components/ui/navbar/navbar"
import { Footer } from "@/components/ui/footer/footer"
import { CartProvider } from "@/components/provider/cart-provider"

import "@/styles/global.css"
import { getCart } from "@/supabase/queries"
import { createClient } from "@/supabase/server"
import { cookies } from "next/headers"

export const metadata: Metadata = {
    title: "WBG SHOP",
    description: "Generated by create next app",
}

const inter = Inter({ subsets: ["latin"] })

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const supabase = await createClient()
    const cartId = await cookies().then(cookies => cookies.get("cartId")?.value)
    const cart = await getCart(supabase, cartId)

    return (
        <html lang="en">
            <body className={`w-full h-screen ${inter.className} antialiased`}>
                <CartProvider data={cart}>
                    <Navbar />
                    {children}
                </CartProvider>

                <Footer />
            </body>
        </html>
    )
}